/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";

import "./globals.css";
import ContentWrapper from "./component/ContentWrapper";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ContentWrapper isSidebarOpen={false} isMobile={false}>
					{children}
				</ContentWrapper>
			</body>
		</html>
	);
}
